import {
  ANTIVAX,
  CHASSE_AUX_RONDS_DE_CUIR,
  CHASSE_AU_WOKISME,
  CONTROLE_POPULATION,
  ENERGIE_100_POURCENT_RENOUVELABLE,
  IMMIGRATION_ZER0,
  ISF,
  LEGALISATION_ARMES,
  LEGALISATION_CANNABIS,
  PRIX_DE_L_ESSENCE,
  SMIC_2000,
  TOUT_NUCLAIRE,
} from '../utils/tags'

export const groups = [
  {
    name: 'gilets jaunes',
    sprite: 'group_base',
    force: 1,
    popularityCost: 1,
    accepts: [SMIC_2000, ISF, CHASSE_AUX_RONDS_DE_CUIR, PRIX_DE_L_ESSENCE],
    rejects: [TOUT_NUCLAIRE],
  },
  {
    name: 'patriotes',
    sprite: 'group_base',
    force: 1,
    popularityCost: 1,
    accepts: [
      IMMIGRATION_ZER0,
      CHASSE_AU_WOKISME,
      CONTROLE_POPULATION,
      LEGALISATION_ARMES,
    ],
    rejects: [ISF, SMIC_2000],
  },
  {
    name: 'etudiants en sociologie',
    sprite: 'group_base',
    force: 1,
    popularityCost: 1,
    accepts: [SMIC_2000, ISF, LEGALISATION_CANNABIS],
    rejects: [IMMIGRATION_ZER0],
  },
  {
    name: 'antivax',
    sprite: 'group_base',
    force: 2,
    popularityCost: 3,
    accepts: [ANTIVAX],
    rejects: [CONTROLE_POPULATION],
  },
  {
    name: 'ecolo',
    sprite: 'group_base',
    force: 3,
    popularityCost: 4,
    accepts: [LEGALISATION_CANNABIS, ENERGIE_100_POURCENT_RENOUVELABLE],
    rejects: [TOUT_NUCLAIRE],
  },
]
